// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANm1ZZxRSo6tZoQlhKtaVv0ywDRG7-haE',
    appId: '1:486744375946:web:3f2d8c7661022bc83ae373',
    messagingSenderId: '486744375946',
    projectId: 'homecare-f2910',
    authDomain: 'homecare-f2910.firebaseapp.com',
    storageBucket: 'homecare-f2910.firebasestorage.app',
    measurementId: 'G-HWFZFX2ZPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtNsl_eobdLUao__iyoKrD_erNtIapyoY',
    appId: '1:486744375946:android:91ab9ba62ba043043ae373',
    messagingSenderId: '486744375946',
    projectId: 'homecare-f2910',
    storageBucket: 'homecare-f2910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDeKXPNeDKJtSJzTO0exrRJw0YK2UQPxs',
    appId: '1:486744375946:ios:6e1a4285be4e6c863ae373',
    messagingSenderId: '486744375946',
    projectId: 'homecare-f2910',
    storageBucket: 'homecare-f2910.firebasestorage.app',
    iosBundleId: 'com.example.mainPjctHomecare',
  );
}
